name: Setup pnpm
description: Simultaneously setup node, pnpm and cache its store. It does not ensure dependencies are up-to-date

branding:
  icon: package
  color: blue

inputs:
  node-version:
    description: Nominate a specific Nodejs version
    required: true
  pnpm-version:
    description: Nominate a specific pnpm version
    required: true
  install-deps:
    description: Boolean to indicate if `pnpm install` should be run. Defaults to `true`
    required: false
    default: true
  restore-modules-from-cache:
    description: Boolean to indicate if the action should automatically cache `node_modules`
    required: false
    default: true
  github-packages-token:
    description: Sets up GitHub Packages authentication with the supplied token if present
    required: false
    default: false

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure GitHub Packages authentication
      if: ${{ inputs.github-packages-token != 'false' }}
      shell: bash
      run: |
        echo "//npm.pkg.github.com/:_authToken=${{ inputs.github-packages-token }}" >> .npmrc

    - name: Setup pnpm
      uses: pnpm/action-setup@v2.2.4
      with:
        version: ${{ inputs.pnpm-version }}
        run_install: ${{ inputs.install-deps }}

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        cache: 'pnpm'
        node-version: ${{ inputs.node-version }}

    - name: Cache modules
      uses: actions/cache@v3
      id: cache-modules
      if: ${{ inputs.restore-modules-from-cache != 'false' }}
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ inputs.node-version }}-modules-${{ hashFiles('pnpm-lock.yaml') }}
